codetriage/CodeTriage

app/models/repo_subscription.rb
test/functional/repos_controller_test.rb
test/vcr_cassettes/create_repo_without_issues.yml

When user have subscriptions and add new repo without issues the mail anyway sent with wrong link with issue number from different repo.

Fix mail sent bug for repo without issues

---

app/models/repo.rb

Also change `downcase_name` from `downcase` to `downcase!` to match `strip_whitespaces`.

Hide callbacks from public API

---

app/controllers/issue_assignments_controller.rb

Fix the undefined method call. Calling the resque method

---

.travis.yml

http://blog.travis-ci.com/2015-03-31-docker-default-on-the-way/

Travis use docker by default

---

app/models/repo.rb
test/unit/repo_test.rb

@igas pointed me on those unused methods. I grep all project's folders and remove them as they are unused. Also I've removed tests for those methods and replace them with test for used `api_issues_path` method.

Remove unused methods from repo model and add test for Repo#api_issues_path

---

Gemfile.lock
app/models/user.rb

Changed the validation checking in able_to_edit_repo? in user model.

Fix validation for edit repo authorization

---

public/404.html

There was no 404 (except the stock one) for CodeTriage

Changed 404.html for use with CodeTriage

---

app/views/application/_nav.html.slim

closing https://github.com/codetriage/codetriage/pull/367 since rebasing has been giving me problems

reordered navbar and added repo link

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/base/_buttons.scss
app/assets/stylesheets/base/_typography.scss
app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/components/_hero.scss
app/assets/stylesheets/layout/_header.scss
app/views/application/_nav.html.slim
app/views/pages/index.html.slim

* Add button class
* Add styles for hero
* Add Styles for navigation

Add styles for header

---

app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/components/_hero.scss
app/assets/stylesheets/components/_repo-list.scss
app/views/repos/_repo.html.slim

Add small refinements to homepage

---

app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_digg_pagination.scss
app/assets/stylesheets/components/_repo.scss
app/assets/stylesheets/layout/_main-application.scss
app/views/repos/show.html.slim
app/views/subscribers/_avatars.html.slim
app/views/subscribers/show.html.slim

Add styles for repo show

---

app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/components/_flashes.scss
app/assets/stylesheets/components/_hero.scss
app/assets/stylesheets/components/_repo-list.scss
app/assets/stylesheets/components/_repo.scss
app/assets/stylesheets/layout/_footer.scss
app/assets/stylesheets/layout/_header.scss
app/views/application/_flashes.html.slim
app/views/application/_footer.html.slim
app/views/application/_nav.html.slim
app/views/pages/index.html.slim
app/views/repo_subscriptions/_list.html.slim
app/views/repos/index.html.slim
app/views/repos/show.html.slim

* Style top navigation
* Style flashes
* Style homepage with subscriptions
* fix bug in subscriptions list

Add styles for logged in user

---

app/assets/stylesheets/base/_forms.scss
app/assets/stylesheets/base/_typography.scss
app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/components/_all-languages-list.scss
app/assets/stylesheets/components/_all-repos.scss
app/assets/stylesheets/components/_content-footer-action.scss
app/assets/stylesheets/components/_content-section.scss
app/assets/stylesheets/components/_digg_pagination.scss
app/assets/stylesheets/components/_hero.scss
app/assets/stylesheets/components/_nav-tabs.scss
app/assets/stylesheets/components/_pagination.scss
app/assets/stylesheets/components/_repo-list.scss
app/assets/stylesheets/components/_repo.scss
app/assets/stylesheets/components/_slats-list.scss
app/assets/stylesheets/components/_subpage-content.scss
app/assets/stylesheets/components/_types-filter.scss
app/assets/stylesheets/components/_user.scss
app/assets/stylesheets/layout/_header.scss
app/controllers/repo_subscriptions_controller.rb
app/controllers/repos_controller.rb
app/views/pages/index.html.slim
app/views/repo_subscriptions/index.html.slim
app/views/repos/index.html.slim
app/views/repos/new.html.slim
app/views/repos/show.html.slim
app/views/shared/_add_repos_list.html.slim
app/views/users/show.html.slim

Add styles for subpages and refactor

---

app/assets/stylesheets/components/_full-width-action.scss
app/assets/stylesheets/components/_repo.scss
app/assets/stylesheets/components/_types-filter.scss
app/assets/stylesheets/layout/_footer.scss
app/views/application/_footer.html.slim
app/views/application/_repos.html.slim
app/views/repos/new.html.slim
app/views/repos/show.html.slim
app/views/users/_form.html.slim
app/views/users/show.html.slim

Fixes: https://github.com/codetriage/codetriage/issues/403 and https://github.com/codetriage/codetriage/issues/402 and thoughtbot footer link

Fix some small bugs

---

public/404.html

Potentially we could just remove the link as well, if that makes more sense.

Update 404 to point to the correct repo page.

---

db/migrate/20151214120117_enable_pg_stat_extension.rb
db/schema.rb

- Running `rake db:migrate` locally has changed `schema.rb` again.

Checked in schema.rb changes

---

config/application.rb

- It was deprecated in https://github.com/rails/rails/commit/07d3d402.

Remove raise_in_transactional_callbacks config

---

Gemfile
Gemfile.lock
app/views/pages/_repos_with_pagination.html.slim
app/views/repos/_repo.html.slim

Reference - https://github.com/rails/rails/pull/18948

Remove multi_fetch_fragments gem as it's part of Rails 5

---

db/migrate/20160613220116_change_issues_title_to_text.rb
db/schema.rb
test/fixtures/issues.yml
test/unit/issue_test.rb

#473
@schneems I thought the simplest way is to change the field to `text`, because like @prathamesh-sonpatki there is no performance issue.

Change issues title to text

---

app/assets/stylesheets/components/_repo-list.scss
app/assets/stylesheets/components/_slats-list.scss
app/controllers/repos_controller.rb
app/helpers/application_helper.rb
app/models/repo.rb
app/views/repos/_repo.html.slim
app/views/shared/_add_repos_list.html.slim
db/migrate/20160827023209_add_stars_count_to_repos.rb
db/migrate/20160827073041_update_stars_count_of_repos.rb
db/schema.rb

#502 Added feature to display stars of repository on main page. See Demo

Added Stars Count Feature

---

Gemfile
Gemfile.lock

Current git source uses git protocol which is insecure, this PR replaces git sources to use https
Review: @schneems

use https protocol instead of git

---

app/assets/stylesheets/components/_repo-list.scss
app/views/repos/_repo.html.slim

Resolved Issue count messed up issue

---

Gemfile

Will make the Rails master build green again.

Add Arel master to Gemfile

---

app/views/users/_form.html.slim
test/integration/user_update_test.rb

Fixes:
https://github.com/codetriage/codetriage/issues/528

Fix edit page not remembering email frequency

---

app/assets/javascripts/application.js

This reverts commit 89084c1d2c80ab642d13b3b039c2a77e5c5fdb6d,
which had broken the data-method='delete' attribute on the Sign Out link,
thereby causing it to match users#show with an :id of 'sign_out'.

add jquery-ujs back

---

app/views/pages/index.html.slim

Fix frontpage by adding cache keys

---

Gemfile
Gemfile.lock
db/seeds.rb

How do I make sure seeds is run for staging/PR apps too?

More detailed seeds

---

app/jobs/application_job.rb
app/jobs/background_inactive_email_job.rb
app/jobs/populate_docs_job.rb
app/jobs/populate_issues_job.rb
app/jobs/send_daily_triage_email_job.rb
app/jobs/send_single_triage_email_job.rb
app/jobs/subscribe_user_to_docs.rb
app/jobs/update_repo_info_job.rb
app/models/issue_assigner.rb
app/models/repo.rb
app/models/user.rb
lib/tasks/schedule.rake
test/fixtures/issue_assignments.yml
test/jobs/send_daily_triage_email_job_test.rb
test/test_helper.rb
test/unit/repo_subscriptions_test.rb
test/unit/user_test.rb

+ Prefer ActiveJob serialization
+ Move code out of models
+ Use Minitest mocks
+ Aggressive find_each batch sizes

Refactor workers

---

Gemfile
Gemfile.lock
Rakefile
config/application.rb
config/boot.rb

Bootsnap
real	0m1.290s
user	0m1.088s
sys	0m0.181s
Bootscale
real	0m2.083s
user	0m1.812s
sys	0m0.238s
Base
real	0m3.065s
user	0m2.177s
sys	0m0.839s

bootscale -> bootsnap, close #549

---

Procfile.development
README.md

Add a Procfile.development file and update README.md on how to use it.
Closes https://github.com/codetriage/codetriage/issues/558

Add procfile development file

---

db/migrate/20170622201545_add_created_at_index_to_issues.rb
db/schema.rb

Up to 8seconds on this query according to heroku

Speed up issue pagination

---

Gemfile
Gemfile.lock

See: https://sentry.io/app5385926herokucom/codetriage/issues/284907048/ 
and https://github.com/lsegal/yard/commit/0b1be5e34d1dcd613ab1b781bedfc80d0a2ff861

Update yard. Fix sentry issue CODETRIAGE-5

---

app/models/user.rb
test/integration/user_session_test.rb
test/integration/user_unsubscribes_test.rb
test/integration/user_update_test.rb
test/test_helper.rb

Fixes codetriage/codetriage#580

Remove :registerable from User devise modules

---

app/jobs/background_inactive_email_job.rb
app/jobs/send_daily_triage_email_job.rb
app/jobs/send_single_triage_email_job.rb
app/mailers/user_mailer.rb
app/models/doc_mailer_maker.rb
app/models/user.rb
test/jobs/send_daily_triage_email_job_test.rb
test/test_helper.rb

Make all emails deliver_later

---

app/controllers/doc_methods_controller.rb
app/controllers/issue_assignments_controller.rb

Fix cases where assignment user was nil.

---

Gemfile
Gemfile.lock

Includes fixes to source maps.

Use sprockets master

---

config/environments/production.rb

https://blog.bigbinary.com/2015/10/31/rails-5-allows-setting-custom-http-headers-for-assets.html

Add cache control headers to assets

---

Gemfile
Gemfile.lock

Github sent me a warning about an out of date version of yard.  PR'ing an update to satisfy that.

update yard per github warning

---

Gemfile
Gemfile.lock
app/assets/stylesheets/base/_buttons.scss
app/assets/stylesheets/base/_lists.scss
app/controllers/users_controller.rb
app/views/users/show.html.slim
app/views/users/token_delete.html.slim
config/routes.rb
test/integration/user_unsubscribes_test.rb

[Close #662] Make delete page not suck

---

app/assets/stylesheets/base/_typography.scss
app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/components/_staticish-pages.scss
app/assets/stylesheets/layout/_footer.scss
app/controllers/pages_controller.rb
app/views/application/_footer.html.slim
app/views/pages/privacy.html.slim
app/views/pages/support.html.slim
app/views/pages/what.html.erb
config/routes.rb

Add static pages

---

Gemfile
Gemfile.lock

note!: I didn't have a working local environment so I couldn't test this. Hope Travis is good enough.

upgrade sinatra due to security vulnerability

---

app/jobs/send_daily_triage_email_job.rb

- Followup of https://github.com/rails/rails/pull/27947
- Silences bunch of deprecation warnings.

Disallow Raw SQL by using Arel.sql for the raw part of the query

---

app/views/application/_footer.html.slim
app/views/application/_nav.html.slim

`alt` tags on `img`s should either have descriptive text (usually) or be intentionally left blank if deemed decorative by context or function.

accessibility improvement: img alt tags

---

Gemfile
Gemfile.lock

Closes #746 (which was bumping to the latest pre-release, rather than latest release).

Bump scout

---

Gemfile.lock

Seeing 16% fewer bytes per page load https://twitter.com/schneems/status/1034801357176426496

Update dalli version

---

Gemfile.lock
config/initializers/rack_timeout.rb

Bump rack timeout

---

config/environments/production.rb

https://twitter.com/schneems/status/1042067988671852544
https://github.com/rails/rails/issues/33907

Don't use `:dalli_store`

---

.travis.yml

- We are deploying directly from heroku now

Remove deploy step from travis

---

README.md

phantomjs now requires brew cask install

---

config/routes.rb

Hey guys,
Opened up this PR just to clean the endpoints a bit.
Nothing much but please review and test if possible.
Cheers,
Bruno

Remove the endpoints generated by 'resources' without a matching controller method

---

test/helpers/application_helper_test.rb

This replaces Pull Request #898 .

Added application helper tests

---

config/puma.rb

- Prompted by https://github.com/rails/rails/commit/84cad15213ea5447ea089

Remove redundant puma config

---

test/functional/issue_assignments_controller_test.rb

Created tests for assignments_controller

---

db/migrate/20190809190610_add_missing_indexes.rb
db/schema.rb

Add the missing indexes on all the tables
Fixes #1046
This should speed up the DB queries
Yes

Add missing indexes

---

.travis.yml
Gemfile
Gemfile.lock

Bump to Ruby 2.6.5

---

app/models/repo.rb
app/views/repos/_docs.html.slim
db/migrate/20191010023214_add_docs_subscriber_count_to_repos.rb
db/schema.rb
test/jobs/parse_docs_test.rb
test/test_helper.rb
test/unit/repo_test.rb

Only parse docs for repos where someone is actively working on docs for that repo.

Only generate docs for subscribed repos

---

CONTRIBUTING.md
db/seeds.rb
test/mailers/previews/user_preview.rb

We should consider executing rake:db as part of the tests to prevent regressions

Update project for new experience

---

app/jobs/populate_issues_job.rb
app/models/issue.rb

When updating issues from GitHub we pull in multiple issues from GitHub. Previously we would then iterate over each of the issues to check to see if they exist in the database individually. With this change, we pull all of the issues (which are paginated at 25 per page?) from the database at once, so we should be seeing 25x fewer queries when updating issues.
Unfortunately, the updates/writes to the database are still 1:1, we can work on that later.

Reduce issue Queries

---

app/models/issue.rb
app/models/issue_assigner.rb
test/emails/send_daily_triage_email_test.rb
test/unit/issue_assignment_test.rb
test/unit/issue_test.rb
test/vcr_cassettes/issue_triage_sandbox_fake_api_responses.yml

Fix missing information from IssueAssigner

---

app/jobs/populate_issues_job.rb
test/jobs/populate_issues_job_test.rb

Was accidentally pulling items from the hash using an internal ID instead of the issue number

Fix populating issues job

---

config/initializers/sentry.rb

The Sentry error jobs are HUGE and take up a lot of space in redis. It's fine for web jobs, but background workers are already running in the background, it takes more work to enqueue them, pop them off, and send them then it does to just send the error report.
In the future I would suggest either sending from the web dynos in a thread or first gzipping the body of the error before storing it in redis.

Don't enqueue background errors in the background

---

app/jobs/populate_issues_job.rb
app/models/github_fetcher/resource.rb

For repos that have been deleted we get a non-error state previously. By checking the status we can stop from assuming the request was successful when in fact it failed.

[close #1140] Check for 2xx status from GitHub

---

app.json
app/models/repo.rb
config/initializers/git_hub_bub.rb
db/seeds.rb
test/fixtures/repos.yml
test/fixtures/users.yml

This script seems to never work, so we're going to start running it with our CI tests. 
Also adding some guards for common problems including: Infinite number of requests to GitHub API as well as a database that has no users with valid GitHub tokens.

Productionize seeds.rb

---

db/migrate/20191029194525_make_timestamps_not_nullable.rb
db/schema.rb

https://twitter.com/schneems/status/1189261712110882818

Re-add not-null to columns

---

db/migrate/20191031142027_add_comment_to_doc_method.rb
db/migrate/20191031144636_add_unique_indexes_to_doc_methods.rb
db/schema.rb
lib/docs_doctor/parsers/ruby/yard.rb
test/jobs/parse_docs_test.rb

Previously logic was coded with an N+1. This commit converts it into a upsert instead.

Use upsert in doc processing background job

---

.travis.yml
Gemfile
Gemfile.lock

Bump Ruby to 2.7.0-preview3

---

.travis.yml

Bump to Ruby 2.7.0-rc2

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/repo_body.scss
app/controllers/university_controller.rb
app/views/application/_nav.html.slim
app/views/university/example_app.md.erb
app/views/university/index.md.erb
app/views/university/picking_a_repo.md.erb
app/views/university/rebase.md.erb
app/views/university/reproduction_code.md.erb
app/views/university/squash.md.erb
app/views/user_mailer/poke_inactive.html.erb
config/routes.rb

Docs for rebasing, providing reproduction code (more general than "example apps" and a stub for an article on "squashing".

University pages updates

---

config/initializers/covid.rb

Add github.com/svs/covid19-supply-chain to Covid repo list

Add github.com/svs/covid19-supply-chain to Covid repo list

---

config/initializers/covid.rb

I have added a project to the list:
nytimes/covid-19-data

Added new project

---

.travis.yml
Gemfile
Gemfile.lock

Upgrade to Ruby 2.7.1
Rails 6.0.3 supports Ruby 2.7 and fixes most of the warnings.

Bump to Ruby 2.7

---

Gemfile.lock

Bump faraday to fix Ruby 2.7 deprecation warnings

---

app/views/university/rebase.md.erb

Removed duplicate paragraph and fixed one typo.
I came across these typos while reading the article and thought that it was a good chance for me to start contributing.

docs(university/rebase): remove duplicate paragraph

---

app/assets/stylesheets/components/_staticish-pages.scss
app/assets/stylesheets/github/markdown-body.css

Fix the University codeblocks

---

app/views/pages/privacy.html.slim

Change mistake in punctuation in the privacy policy.
Just a simple fix for a grammatical mistake in the privacy policy.
I'm not sure if I have to open an issue for this. If I do, please inform me.
Correct grammar.
I didn't test this. Please tell me if I have to do so or this PR won't be merged.

Change mistake in punctuation in privacy policy

---

README.md

The Twitter link on the README uses `http` which is not secure. This pull request updates the link to use the secure `https`

Update link to use https

---

app.json

Update tests for Heroku-16

---

Gemfile
Gemfile.lock
test/test_helper.rb

Updates Ruby to version 3.1.2 (+ dependencies required to fix problems and deprecation warnings)
#1701 
--
Test suite were ran locally.
--

Upgrade Ruby to 3.1.2

---

test/functional/users_controller_test.rb

added tests for `show`, `update` and `token_delete` in `users_controller`

add more tests for UsersController

---

test/functional/doc_methods_controller_test.rb

Related to #862 
I wasn't able to test one of the methods on the controller because it had a couple of errors that made the method not function properly. I would be able to test it if my fixes were accepted (#944).

Added tests for doc_methods_controller

---

test/functional/users_controller_test.rb

There was a test missing an assertion, this fixes it 
#975

Add missing assertion to test

---

.github/workflows/main.yml
config/database.ci.yml

Set up GitHub Actions to run tests to check the PRs on GitHub.
I add YAML file to define workflow.
#1685
CI will help maintainer, contributors and users of CodeTriage to know the code work well, or alert soon when something is broken.  
I created the same PR to another forked repo ( https://github.com/gregmolnar/CodeTriage/pull/1 ), and run CI.
GitHub actions are triggered by pushing, and all jobs are success.

Port tests over to GitHub Actions

---

app/views/topics/show.html.slim

Updated. the heading in hacktoberfest homepage
Changed 
``` All repo with with label hacktoberfest. ``` 
to this
``` All repo with label hacktoberfest. ```
#1798 
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] I have read the **CONTRIBUTING** document.
- [] I have added tests to cover my changes.

Fix. heading in hacktoberfest homepage

---

.github/workflows/main.yml

GitHub Actions workflow prints the following warning.
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
This PR updates [actions/checkout](https://github.com/actions/checkout) to v4 in order to suppress the warning.
Want to suppress the deprecation warnings.

Bump actions/checkout from v2 to v4

---

app/models/user.rb

Fixes issue https://github.com/codetriage/CodeTriage/issues/1780

Remove missing association of repo_assignments from User model.

---

Gemfile
app/models/repo.rb

Use the "newer" style of declaring private and make update_repo_info public

Update private repo methods
