codetriage/CodeTriage

app/views/repos/index.html.erb

Hi.
This button seems to be unnecessary. There is already a 'Submit a Repo' button linking to `new_repo_path` that is rendered by the partial called in this view.
Wonderful idea! I hope to be able to contribute more soon.
All the best,
O-I

Removes extraneous 'Add a Repo' button

---

app/mailers/user_mailer.rb

Changes `UserMailer.send_daily_triage()` to use `@assignments.size` as the argument to `"Issue".pluralize()` rather than `@assignments.count`. I'm not too familiar with Ruby so I don't know if this will actually fix the underlying issue, but I presume that since `@assignments.size` is returning the correct number of issues, then the behaviour will either become fixed or stay the same. Addresses #312.

Determine plurality of "issue" using .size method

---

.editorconfig

I've noticed recently that a lot of pull requests are getting dirty because of the different coding style of all contributors, so a way to try to get this to work is editorconfig. The contributors just need a plugin on their default Code Editor. 
Please check their website: http://editorconfig.org

.editorconfig to make a default indenting style

---

.travis.yml

Travis now bundled with higher bundler version, so we don't need to install it.

Remove tmp bundler fix for travis

---

README.md
app/mailers/user_mailer.rb
app/models/email_decider.rb
app/models/user.rb
app/views/layouts/application.html.slim
test/unit/email_decider_test.rb

- Added docs, improved variable names.
- Added ability to only send 1 email a month.
- Using time_ago_in_words on date in subject. I think the running date count accidentally encourages people to make the count go higher. 
- Added debugging info we can grep in papertrail for in production timing (i'm seeing behavior in production I cannot produce locally).
- Remove Heroku branding mention.

Update email decider

---

app/controllers/users_controller.rb
test/integration/user_unsubscribes_test.rb

If a user clicks an unsubscribe link twice by mistake, instead of seeing a crash page they will be redirected and receive an flash notice. This will let them know that their account wasn't found and that either it was already deleted, or perhaps they changed their GitHub username since signing up. Discussed in #339.

Flash error when user repeat unsubscribes

---

app/views/application/_footer.html.slim
app/views/layouts/application.html.slim

UPDATE: Changed container-narrow to container. Less whitespace and better looking IMO
container-narrow to container

Added footer with CodeTriage Github link and width fix

---

app/views/users/after_signup/set_privacy.html.slim
app/views/users/new.html.slim
app/views/users/show.html.slim
config/routes.rb

We had 3 duplicated routes to `sign_up`. Also we had `/users` and `/users/new` without actual logic in controller. It's not trivial to remove unused user creation, thats why `devise_for` looks like this now, but it's still keeps `:registerable` in model.

Cleanup users paths

---

db/migrate/20150629002651_remove_repo_name_from_repo_subscriptions.rb
db/migrate/20150629010617_remove_user_name_from_repo_subscriptions.rb
db/schema.rb
test/fixtures/repo_subscriptions.yml

Removed the user_name and repo_name columns since they are not being used and the table already contains user_id and repo_id which references the corresponding user and repo for that particular repo_subscription.

Modify repo_subscriptions table

---

app/controllers/badges_controller.rb
app/models/repo.rb
config/initializers/mime_types.rb
config/routes.rb

Badges allow visitors to see at a glance how many people are subscribed to your project and, the "status" of issues. For now this is a hard coded value based on the number of issues, but we could change it to a ratio or something else more clever.
I worry that larger projects would shy away from putting a red badge on their repo, but then again maybe it would encourage them to keep issue counts low. Curious on other's thoughts here. Ideally a green badge should be a point of pride.
Add a modal to the badge that gives url for easy copy

Add badges

---

app/views/pages/index.html.slim

so that 'C#' is mapped to 'C%23' for language searches (issue #412)
I know in the issue you proposed changing the UI framework but it's simple enough to patch up the existing AJAX too.

URI encode filter value for query string

---

app/models/repo.rb

Ordering all languages alphabetically makes finding your favorite languages in the preferences much easier, before:
After:

Order all_languages alphabetically

---

.travis.yml
Gemfile
Gemfile.lock

This will allow Rails to have better integration testing on existing,
and production-running apps. As well, the `RAILS_MASTER=1` build is in
the allowed failure category, so it will not disrupt the normal CI
procedure for Code Triage.
\c @schneems

Add Rails master to Travis CI build

---

app/assets/stylesheets/components/_avatar.scss

iPhone 6+
iPhone 5
Sorry for being a narcissist. I really like the picture :trollface:

Change from calc() to explicit value inside media query (Fixes: #422)

---

app/controllers/pages_controller.rb
test/functional/pages_controller_test.rb

@schneems 
This should resolve #437.
I have added headers to the response of the index action in the
pages controller which prohibits the browser from caching the page.
A new test in `pages_controller_test.rb` has also been added.
Tested with Chrome on OS X

Explicitly disable caching for Pages#index

---

app/views/pages/index.html.slim

This Resolves #429
When paginating and then changing languages, the `page` URL parameter persisted.
It seems that it would be better to reset to the first page when moving between
languages to prevent the following behaviour:
1. Language "A" has > 10 pages
2. Language "B" has < 10 pages
3. User on Page 12 of language "A" selects language "B"
4. User is shown empty page of language "B" results since language "B" results
can not fill 12 pages
This code simply extends the existing javascript solution.

Reset to First Page on Language Switch

---

app/models/repo.rb

It appears that `Repo#find_by_full_name` triggers some memory bloat when called by repos with many issues:
I believe the offender is the `includes(:issues)`, which thankfully, [I don't believe is used by any of the callers](https://github.com/codetriage/codetriage/search?utf8=%E2%9C%93&q=find_repo&type=Code).
Here's a massive one-line PR to address this.

Repo#find_by_full_name triggers memory bloat w/ :issues include

---

app/helpers/repos_helper.rb
app/views/repos/show.html.slim

As @schneems suggested in #434 I've changed "I want to triage..." button behavior. 
When user is not signed the button redirects to authorization page and then user is redirected to the repository page. The user must click the button once again, but there is no 404 error page.
Behavior for logged user remains the same.

Fix 404 error when anonymous user tries to triage a repo

---

app/assets/stylesheets/base/_forms.scss
app/controllers/users_controller.rb
app/models/email_decider.rb
app/models/user.rb
app/views/users/_form.html.slim
app/views/users/show.html.slim
db/migrate/20160606060546_add_email_frequency_to_users.rb
db/schema.rb
test/fixtures/users.yml
test/unit/email_decider_test.rb

We don't want a user setting a "default" value to short circuit our deciding logic. We still want to back off if they're not interacting so they don't get burned out and turn off  emails. 
This PR includes commit from #472

Refine user selectable email frequency

---

Gemfile.lock
config/initializers/git_hub_bub.rb
config/scout_apm.yml

There is still a warning from scout_apm telling us that things are working fine. I opened an issue https://github.com/scoutapp/scout_apm_ruby/issues/49

Avoid all the warnings we can

---

Gemfile
Gemfile.lock
Rakefile

Before we were averaging 14.94 seconds for a compile with a cold cache. Now we're down to 10.16 seconds. This PR gives us a roughly 31% increase in compile speed.

Use Sassc native extension for speed boost.

---

app/assets/stylesheets/base/_forms.scss
app/assets/stylesheets/components/_repo.scss

This PR adds a css styling across all select boxes to ensure black text colour.
With this PR issue #494 can be closed, and I believe #432 as well.
Select value already defaults to "daily", as mentioned on #494, so nothing else had to be done.

Ensure select text colour is black

---

app/models/repo_subscription.rb
app/views/repos/show.html.slim
test/functional/repo_subscriptions_controller_test.rb

#482 
Fixes bug where users must select issues to triage before selecting docs, and incorporates minor view tweaks to standardize the two.

Enable separate doc registration #482

---

README.md

Change README to use `heroku local`.
Forman start failed for `release rake db:migrate` command.
Use `heroku local` instead. See #485 for more details.

[ci skip] Use heroku local instead of foreman

---

README.md

* Using `Heroku Local` instead of `Foreman`
* Change port numbers to `3000` instead of `5000` as specified in the
`.env` file instructions.

[ci skip] Small fixes in the README

---

app/assets/stylesheets/components/_slats-list.scss

Before:
After:
Looks the same in Chrome and Safari.

Improve layout of user settings content section

---

app/jobs/mark_issue_closed_job.rb
test/jobs/mark_issue_closed_job_test.rb

`MarkIssueClosedJob` is unused and doesn't have any implemented. This PR 🔥's dead code.

remove unused dead code

---

app/helpers/application_helper.rb
app/views/application/_default_meta_tags.html.slim
app/views/application/_head.html.slim

Added meta tags helper to render default or custom meta tags inside the helper. This fix will resolve issue#513.
Given default meta tags are:
Name: CodeTriage
Description: Help out your favorite open source projects and become a better developer while doing it
To render custom meta tags:
just use `content_for(:meta_tags)` block and define your meta tags. That's it!
This is how it shows to facebook:

Added meta tags helper to render default or custom meta tags inside the helper

---

Gemfile
Gemfile.lock

These two gems are preventing CodeTriage from running CI against Rails
master. In the case of coffee-rails, it had a version restriction that
required the gem version being bumped. In the case of rollbar, the
version ahd to be bumped because the previous version has been using the
now removed `alias_method_chain`.

Bump coffee-rails and rollbar gems

---

.travis.yml
Gemfile
Gemfile.lock

Not sure why but `bundle install` does not update the `Gemfile.lock` to 2.4.

Ruby 2.4 Compat

---

app/assets/stylesheets/components/_repo-list.scss

Hey there 👋
I noticed a small graphical bug while hovering over repo items. Attached is a gif showing the graphical glitch. When hovering over any `.repo-item`, all other `.repo-item`'s are affected.
It seems that while hovering over a `.repo-item`, the corners of the `.repo-item-header` are showing for a split second. A simple solution is to round the top corners of the `.repo-item-header` to match the `.repo-item`.

Add top border radius to repo item headers.

---

app/views/user_mailer/daily_docs.md.erb

Congratulations on the merging of docsdoctor.org into codetriage.com
This removes a small remnant. docsdoctor.org currently goes to a 'There's nothing here, yet.' Heroku page.

Remove reference to docsdoctor.org in docs email

---

README.md

Follow on from:
https://github.com/codetriage/codetriage/pull/526

Update readme to prefer `db:schema:load` over `db:migrate`

---

app/views/doc_methods/show.html.slim

Fix for removing double quote from open path in edit section of docs methods

Removed the trailing double quote mark present in the open file path in doc_methods show page in edit section of the page.

---

app/models/user.rb
db/migrate/20170604190958_add_old_token_to_users.rb
db/schema.rb
lib/tasks/schedule.rake

- Exit early if API is reported as being down
- Check same token multiple times, only remove if it returns `false` 3 times in a row.
- Archive token in `old_token` instead of just deleting, allows for recovery in case of another mass token invalidation event. 
We should enhance the RequestError from GitHubBub so that it has the response object in it, so we can detect the status code. If GitHub returns anything other than a 404 for that endpoint it means such as a 500 it means we should not delete the endpoint.

[close #557] Harden Token Check

---

app/jobs/send_daily_triage_email_job.rb
test/jobs/send_daily_triage_email_job_test.rb

This checks if any of user.repo_subscriptions has a last_sent_at that is set to within the last 24 hours. If that's the case then it will abort the job.

Fix sending duplicate emails

---

app/models/repo.rb
db/migrate/20170629151616_add_unique_index_to_repos.rb
db/schema.rb
test/integration/repos_test.rb
test/unit/email_rate_limit_test.rb
test/unit/repo_test.rb

According to Heroku, we have a query that accounts for 80% of all time spent in postgres
```
$ heroku pg:outliers
total_exec_time  | prop_exec_time |   ncalls    |   sync_io_time   |                                                                                       query
------------------+----------------+-------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
3790:50:52.62102 | 80.2%          | 100,727,265 | 727:08:40.969477 | SELECT  ? AS one FROM "repos" WHERE LOWER("repos"."name") = LOWER($1) AND ("repos"."id" != $2) AND "repos"."user_name" = $3 LIMIT $4
```
Where did it come from? Turns out, it's not in my code. It was added …

Fix Postgres CPU burn

---

.gitignore
README.md

It's quite possible I missed something (I see many forks, so seems odd I'd be the first to have this issue). But I was unable to OAuth locally without first creating my own app on GitHub (the default keys suggested above in the README resulted in an error). It's quite possible I misread the README, but I thought this might be helpful. Happy to make any other adjustments if this is useful.

Add own app to readme

---

app/views/repos/new.html.slim

The use of the `active` class on all 3 panes means that "owned",
"starred", and "watched" repos are all displayed, despite the fact that
the UI only has the "owned" tab as active. This is misleading/confusing.
While I think there's some benefit to an "all" option (scrolling is
easier than clicking) and therefore it's possible that this change
results in a decrease in repo added, I think it's worth the improved UX
(and the decreased metric can likely be remedied by ading and defaulting
to an "all repos" tab).
It appears this bug was introduced way back in
324c1a0358f18eba7ce75eee9fb2406baac25f9a when the feature to add starred
and watched repos was introduced.

Only show repos I own by default

---

app/models/issue.rb

Both `Issue#fetcher` and `Issue#comments_fetcher` were using the same instance variable (`@fetcher`) when memoizing.  
Wasn't sure if it was worth adding a test to expose the memoization bug or not. Let me know if you feel strongly about it, and I can add one.

Fix fetcher memoization bug

---

Gemfile
Gemfile.lock
config/initializers/mini-profiler.rb
config/initializers/sidekiq.rb

Multiple apps can connect to default sidekiq. Be a good neighbor by using a namespace locally.

Use a namespace locally

---

app/jobs/populate_issues_job.rb
app/models/github_fetcher/issues.rb
app/models/github_fetcher/resource.rb
app/models/repo.rb
test/jobs/populate_issues_job_test.rb
test/unit/github_fetcher/issues_test.rb

Changing options blows the cache.
+ Add page change method
+ Move last page? to Resource
+ Remove state setting on job, b/c it's just the default.

Fix Github response memoization

---

app/views/doc_methods/show.html.slim

Git doesn't have a `co` command, I think we want `checkout` instead. The original author probably had it as an alias.

Use git checkout in instructions instead of git co

---

.travis.yml

As discussed with @elliotthilaire on #619 
> I wasn't suggesting we make the build green if it shouldn't be. Instead if the rubocop and tests fail, we can find out in a single build instead of two.

Split test and rubocop tasks for Travis

---

app/jobs/send_daily_triage_email_job.rb
test/jobs/send_daily_triage_email_job_test.rb

Fixes https://github.com/codetriage/codetriage/issues/615
Checking for a sent email in last 24 hours means that if you change the preference to earlier, the email will still get held back until the 24 hours is up, and this cycle will continue.
Instead we check if an email has been sent since the start of the day.
Thanks to @charlietarr1 for pairing with me on this.

Fix email not sending at preferred time

---

app/controllers/badges_controller.rb

We don't need to raise this further because it's not our fault that
shields.io isnt responding promptly.
Fix CODETRIAGE-D1

Fix this route sometimes timing out, return meaningful status.

---

app/models/issue_assigner.rb

Fix CODETRIAGE-DY
Sometimes this fails because an issue is already assigned. In that case
we don't want to raise, just ignore and keep moving.

Issue assigner shouldn't raise

---

README.md

I setup codetriage locally and updated a few things in the README to match my experience.
* Per [Heroku docs](https://devcenter.heroku.com/articles/heroku-local) default port is 5000
* Updated link to register the app with github and updated the title to match the github page
* removed GITHUB_API_KEY parameter that was not needed during my setup

update README to match my experience setting up

---

app/views/repos/show.html.slim

Updated the links in the pagination on repos#show so that they link you to an anchor at the top of the issues section, rather than the top of the page where you have to scroll down to keep browsing.

link pagination directly to issues list

---

app/mailers/user_mailer.rb

When UserMailer render the emails, the view have a N+1 since it is trying to get properties from issue, user and repo relations on the loop of assignments.
https://github.com/codetriage/codetriage/blob/b3d7a1186e21608052f48d9a9c86eb4c400b7b40/app/views/user_mailer/send_daily_triage.md.erb#L6-L16
Also:
- removing an extra assignment on the assignments ivar
- moving the set_and_check_user guard before performing the query

Remove N+1 on UserMailer#send_daily_triage

---

test/unit/email_rate_limit_test.rb

This PR is to address #541
This test was computing date ranges for daily notification, but then asserting EmailRateLimit behavior based on a weekly preference.  Whenever the random value for clicked_ago was divisible by 7, the last assertion would fail, but in all other cases it passed.
I rewrote the assertion to pass a daily preference (to match the logic of how clicked_ago was generated), then added similar assertion to other intervals.
I ran this one-liner to confirm before and after behavior.
```
for ((i=1;i<=100;i++)); do rake test TEST=test/unit/email_rate_limit_test.rb ; done;
```

Fix issue with unreliable test

---

Gemfile
Gemfile.lock
app/controllers/repos_controller.rb
app/views/layouts/application.html.slim
app/views/repos/list.html.slim
app/views/repos/new.html.slim
config/routes.rb

As requested on #594, this uses render_async to fill in repos#new.
Big thanks to @nikolalsvk for cutting the new release of render_async on https://github.com/renderedtext/render_async/pull/35

use render_async to speed up repos#new, resolves #594

---

app/models/repo.rb
app/models/user.rb

Spending close to 40% of time executing queries with `RANDOM()` in them.: 
```term
$ heroku pg:outliers
14:52:35.890252 | 19.9%          | 186,846    | 02:38:39.448613 | SELECT  "repos".* FROM "repos" WHERE (repos.id not in (?,?)) ORDER BY random() LIMIT $1
08:59:35.017667 | 12.1%          | 2,532,339  | 00:01:13.506894 | SELECT  "users".* FROM "users" WHERE ("users"."github_access_token" IS NOT NULL) ORDER BY RANDOM() LIMIT $1
```
Instead we can figure out the largest possible ID, generate an ID between 1 and that number then find a record greater than or equal to that ID.
Here’s the current query with `RANDOM()`:
```
=> EXPLAIN ANALYZE SELECT  "users".* FROM "users" WHERE ("users"."github_access_token" IS NOT NULL) ORDER BY RANDOM() LIMIT 1;
QUERY PLAN …
```

Don’t call RANDOM() on large tables

---

app/models/user.rb

When pending issues exist, do not assign new issues. We do this for the case where this method is being retried.

[close #614] Don’t assign issues, if pending

---

app/mailers/user_mailer.rb
app/models/repo.rb
app/views/user_mailer/poke_inactive.html.erb
app/views/user_mailer/poke_inactive.text.erb
app/views/user_mailer/send_triage.html.erb
app/views/user_mailer/send_triage.text.erb
test/functional/user_mailer_test.rb
test/unit/repo_test.rb

This resolves the extra code noted on #587.  As noted there, full_name is not available until the record is persisted, but (at least now) the tests all pass and the app seems to work anyway so I went with it as-is.  If it turns out that's a problem, please point me in the right direction so I can add a test and adjust this to get it passing.

remove Repo#path in favor of Repo#full_name, closes #587

---

app/controllers/repos_controller.rb
app/views/repos/show.html.slim

Offset pagination has the nasty habit of being REALLY slow when your offset is large. We don’t need random access for issues and doc methods, honestly having them on this page I don’t even think are that useful, but it looks nice.
This reduces the load on the DB from offset pagination and also removes the need to count all records on every page load. 
These counts add a non-trivial amount of DB load:
```
493:04:18.903353 | 10.4%          | 101,625,003 | 52:09:48.599802  | SELECT COUNT(*) FROM "issues" WHERE "issues"."repo_id" = $1 AND "issues"."state" = $2
```

Keyset pagination on Repo#show

---

Gemfile
Gemfile.lock
app/controllers/badges_controller.rb

The badge endpoint is one of the slower endpoints. By not relying on a network connection we can instead build our own SVG in a fraction of the time.
This code is a port of https://github.com/badges/shields/blob/master/lib/make-badge.js script and the flat template https://github.com/badges/shields/blob/master/templates/flat-template.svg. 
For the weird font size of 10.858, I adjusted prawn’s size until it matched the output of the same string from sheilds.io (running locally).

Faster badge response times without network request

---

README.md

Seems puma is running application in default port `3000`.
https://github.com/codetriage/codetriage/blob/f020070f0c44c79a90ff4f2c7c0e8ccb956a7f70/config/puma.rb#L14

Updated application port to 3000

---

Gemfile
Gemfile.lock

Hello, Code Triage maintainers! 
I'm writing on behalf of the team at [Skylight](https://www.skylight.io), and following up on a conversation between @schneems and @chancancode. As you've likely heard, our team is planning on making Skylight free for open source projects this year, and we wanted to offer you a free beta account to use Skylight on your Rails app for free!
We wanted to make this process as easy for you as possible, so this PR is the first step in that direction. It adds the `skylight` agent to the project's Gemfile. 
Once this is merged/deployed, you will just need to set an ENV variable containing your API key, which we can send you privately over DM. Until that variable is set, you will see a message like this in your application logs: `[SKYLIGHT] Unable to start, see the …

Add skylight gem for Skylight for Open Source

---

app/views/subscribers/show.html.slim

Looks like your editor chomped off a space in 49b243f1a295ecb19b4e2efa75aa38bd6ec5e2bf

Re-add space between static copy and repo name

---

README.md

[Preview this change](https://github.com/chancancode/codetriage/blob/73de5ae0d357ae94a96cae30eacdeba012b7b276/README.md)
I finally figured out why Skylight wasn't working! Turns out, an old ENV var from 2013 was shadowing the token we are trying to set 😄 
Now that it is working, this will link to the public (no login needed) performance dashboard to help contributors find it. (Plus it will turn grey if this stops working again.)

Add performance monitoring badge

---

app/controllers/pages_controller.rb
app/models/repo.rb
test/unit/repo_test.rb

Hi,
I thought it would be useful to hide repos that a user is subscribed to from the "projects that need help" section so that they don't show up more than once on the user's dashboard when they are logged in.
As a user who is subscribed to Repo X, when I am logged in to the home page I see Repo X in the "Repos you are currently helping" section as well as in the "Open Source projects that need your help" section.
As a user who is subscribed to Repo X,  when I am logged in I only see Repo X in the "Repos you are currently helping" section.
This PR is a working example.  Let me know if you think this is useful and I can finish it up and add tests.  I'm also open to any other feedback on implementation, code style, etc.
Thanks!

Don't show repos in "Repos that need help" section when user is subscribed

---

app/controllers/pages_controller.rb

Before this change, we were doing two queries per request to get the count of users and repos to generate the description meta tag (see screenshot below). Presumably, we don't actually care that these numbers are super up-to-date, so we can cache it up to an hour (same as the similar text in the [template's h2 tag](https://github.com/codetriage/codetriage/blob/633948dad71f072712dc322c514142f7df2f2a25/app/views/pages/index.html.slim#L3)).
[![screen shot 2018-04-10 at 4 13 20 pm](https://user-images.githubusercontent.com/6921610/38588351-3e3ccd98-3cda-11e8-8848-883794bf2215.png)](https://oss.skylight.io/app/applications/IfSk4kDAh56r/1523380440/6h/endpoints/PagesController%23index?responseType=html)

Cache the description meta tag

---

app/controllers/pages_controller.rb
app/views/repos/_repo.html.slim

We noticed this problem recently:
When rendering the repo "cards" on the homepage, we use the collection caching feature to avoid multiple roundtrips to the cache store (the "cache read multi" in Skylight). However, when there are cache misses, we end up doing another separate read/write to the cache store per card, and then we do another write at the end from the collection caching.
You can see this in the logs as well:
```
Cache read_multi: ["views/repos/1894-20180413141703167092/b201d971de1a77b9f19a62934e479a96", "views/repos/1245-20180413141214948480/b201d971de1a77b9f19a62934e479a96", "views/repos/3353-20180413142449772302/b201d971de1a77b9f19a62934e479a96", "views/repos/987-20180413140921805080/b201d971de1a77b9f19a62934e479a96", …
```

Fix caching

---

README.md

Clarify that Postgres is required, not just recommended. For instance, CodeTriage has Postgres-specific migrations like 20151214120117 (EnablePgStatExtension).

Clarify in README that PostgreSQL is required

---

app/controllers/doc_methods_controller.rb
app/controllers/issue_assignments_controller.rb
app/mailers/user_mailer.rb
app/models/email_rate_limit.rb
app/models/mail_builder/grouped_issues_docs.rb
app/models/user.rb
app/views/user_mailer/send_daily_triage.md.erb
app/views/users/_form.html.slim
db/migrate/20180716144937_add_streak_to_users.rb
db/schema.rb
test/unit/user_test.rb

The current method “days since you clicked” is a bad incentive. The number grows while you do the wrong thing and it gets set back to zero when you do the right thing (click an issue). Instead, we move to positive reinforcement. When the user clicks an issue they see the count incremented by one. When the miss clicking on an email, the count is decremented (so if someone takes a short break they don’t lose their entire streak, but if they go away entirely it will.
In the future, we can add some more semantic context around the number. For instance, we might give the user positive reinforcement when `emails_missed_since_click` is 0 (since that means they are active recently), and some negative reinforcement if this value is higher (indicating that their streak is going down). We might also …

Introduce Streaks model of counting interaction

---

app/views/user_mailer/send_daily_triage.md.erb

This should change it from this:
>Your contribution streak is at 1. Click on a issues link below to keep going. The goal is still to learn. Start taking notes on what you observe, how is it different today than what you saw from the last email? How is it the same?
To this:
>Your contribution streak is at 1. Click on a contribution link below to keep going. The goal is still to learn. Start taking notes on what you observe, how is it different today than what you saw from the last email? How is it the same?
A subtle change but I believe it to be a worthwhile one.

Change grammar 'a issues link' to 'a contribution link'

---

app/models/user.rb

This should be more representative of actual activity.

The “last” subscription may not have any issues

---

Gemfile
Gemfile.lock
app/controllers/repo_based_controller.rb
app/mailers/user_mailer.rb
app/models/mail_builder/grouped_issues_docs.rb
app/models/repo.rb
test/emails/send_daily_triage_email_test.rb
test/fixtures/issue_assignments.yml
test/fixtures/repo_subscriptions.yml
test/fixtures/repos.yml
test/unit/mail_builder/grouped_issues_docs_test.rb
test/unit/repo_test.rb

Right now all the issues that I get are in the same order every time. It’s a bit monotonous. I don’t want people always only clicking on the first one, or getting in the habit of scrolling past the first one etc.
In the future, we can do something a bit smarter. Perhaps we can order by reverse clicked time so the repos that are most interesting are at the top.
To make a change like that I would likely want to introduce an actual A/B testing framework to see if it changes people’s behaviors (i.e. more clicks etc.).
In general, Random seems to give people the impression that the algorithm is smarter than it really is. Any behavior we implement should be able to beat “random”, so this is a good baseline.

Shuffle order of issues in email

---

app/views/application/_nav.html.slim

This is a quick stab at a `<noscript>` message. I wasn't sure where you'd want the the tag to live, `_nav` seemed like a reasonable spot, but let me know if you'd prefer something else.
Also I didn't know if you'd object to me essentially hijacking the flash message styling for this warning. It seems to fit well, but I'd understand if you wanted to do that styling differently.
How it should look:
A link to easily disable javascript in chrome dev tools in case it's not top of mind: https://stackoverflow.com/questions/13405383/how-to-disable-javascript-in-chrome-developer-tools

Add simple noscript message warning to enable JS

---

app/models/repo_subscription.rb
app/models/user.rb
test/mailers/previews/user_preview.rb

The warning says:
>   DEPRECATION WARNING: Dangerous query method (method whose arguments
>   are used as raw SQL) called with non-attribute argument(s): "random()".
>   Non-attribute arguments will be disallowed in Rails 6.0. This method
>   should not be called with user-provided values, such as request
>   parameters or model attributes. Known-safe values can be passed by
>   wrapping them in Arel.sql().
There's currently only one deprecation warning in the test suite, but it
seems like a fairly straightforward change to make throughout as there
was no user input being used, just plain RANDOM() calls.

Address deprecation warning

---

app/assets/javascripts/user_email_time_of_day.js

The current implentation leaves the original order (UTC) but just
changes the labels so it appears out of order to the user. The
proposed change is not amazing code, but seem effective to order based
on the user's local time.
Advantages: quick, easy, effective
Disadvantages: not the prettiest code, breaks handlers I believe (but
there are none that I see)
I thought this might be a good time to pick a time as the default. It
seems unlikely that midnight UTC is many people's first choice, so I
figured after work-ish (7PM local) would be a reasonable default.
References:
- jquery select sort: https://stackoverflow.com/a/7466196
Resolves #721.

Sort the select options after converting to local time

---

app/controllers/doc_methods_controller.rb
app/models/git_branchname_generator.rb
test/unit/git_branchname_generator_test.rb

Resolves #688 which reports an issue when there is a question mark in the
method name. git spec states that question marks are not allowed. I took
more conservative approach and only allowed numbers, letters, and
underscores.
I also converted periods to pounds:
`Payment.charge` -> `Payment#charge`

Update formatting for branch names

---

app/models/repo_subscription.rb

I'll start this by saying that caching in rails is NOT a strength of mine. I figured solving this issue would give me the chance to get a bit smarter on the matter. Fortunately/unfortunately I got it to work sooner than I thought.
Fortunately: it seems to work.
Unfortunately: I feel like it was too easy so I'm afraid it's not correct 😄.
As you see, all I did was add `touch: true` in `RepoSubscription` on the `belongs_to: repo` association.
The obvious thing I could have messed up was just testing it incorrectly in dev mode, but I did set `rails dev:cache` (thanks rails, that's quite nice). So I think I got that part right. I manually tested this by subscribing/unsubscribing after setting the cache mode in dev with and without the `touch: true` beings set so I _think_ it works, but I lack …

Force repo show page to invalidate cache

---

app/assets/javascripts/user_email_time_of_day.js

* I introduced a bug in the way that I selected the email time of day
because I was ALWAYS selecting the default time instead of only when the
user hadn't selected a date.
* There are a number of ways to do this, but it's not something anyone
asked for (or that anyone probably needs). No code being better than
more code let's just remove it for now?

Revert default email time of day selection

---

app/assets/stylesheets/base/_typography.scss
app/views/application/_nav.html.slim

Visually you shouldn't see a difference, but a screen reader will now tell the user that the link is to "Code Triage Home". I think that will be an improvement.
* Style taken from bourbon version 5.1.0 to allow for providing text to screen readers but hiding for visual users. This should be removed when bourbon is upgraded.
https://github.com/thoughtbot/bourbon/blob/v5.1.0/core/bourbon/library/_hide-visually.scss

accessibility improvement: Add text to logo

---

app/views/repos/_repo.html.slim

Update heading tags to be hierarchical. `h4` -> `h3`. The styling looks the same to me visually and now the page structure will not skip the h3 tags.

accessibility enhancement: hierarchical heading tags

---

app/jobs/send_daily_triage_email_job.rb
app/mailers/user_mailer.rb
db/migrate/20180820155654_add_last_email_at_to_user.rb
db/schema.rb
test/fixtures/users.yml

The same job should not increment `raw_emails_since_click` more than once.
This will prevent that (hopefully).

[close #744] Make streak count update idempotent

---

app/controllers/doc_methods_controller.rb

The `doc_methods#show` view is showing the `GitBranchnameGenerator` object itself, not the branch name, because `branchname` isn't being called on the object. This PR adds a call to `branchname`.

Call branchname on GitBranchnameGenerator to get branchname

---

app/mailers/user_mailer.rb
app/models/repo.rb

changed the way @random_repo gets a random user so it never returns a `nil` and consequently fixing the intermittent error on the test.
Also fixed a tiny typo in `repo.rb` :smile:  #801

fix intermittent test in user_mailer_test

---

app/assets/stylesheets/base/_forms.scss

In _**./app/assets/stylesheets/base/_forms.scss**_ added:
```scss
#{$all-text-inputs},
select{
...
color: inherit;
}
```
[#1097](https://github.com/codetriage/codetriage/issues/1097)
This minor change improved readability thus avoiding typos in repo url inputs.
|Bug | Fixed|
| :-: | :-: |
|![codetriangle-bug](https://user-images.githubusercontent.com/49572628/65978833-61b90280-e442-11e9-9b25-8772200ee553.png) | ![codetriangle-fix](https://user-images.githubusercontent.com/49572628/65978838-6382c600-e442-11e9-9d1e-349fa22f37e7.png)|

Fixed url input color not readable

---

app/jobs/send_daily_triage_email_job.rb
app/models/doc_mailer_maker.rb
app/models/repo_subscription.rb
test/emails/send_daily_triage_email_test.rb

With this code the query becomes:
```
SELECT "doc_methods".* FROM "doc_methods"
WHERE "doc_methods"."repo_id" = $1
AND (doc_comments_count > 0)
AND "doc_methods"."active" = $2
AND (doc_methods.id NOT IN (
SELECT "doc_assignments"."doc_method_id" FROM "doc_assignments" WHERE "doc_assignments"."repo_subscription_id" = 84189)
)
AND "doc_methods"."skip_read" = $3
ORDER BY RANDOM()
LIMIT $4
```
Previously it would grow unbounded since we were manually mapping and passing in IDs:
https://gist.github.com/schneems/b568ad370c6b90ab236ebd455f4a20a5

Make query much smaller

---

app/models/github_fetcher/repo.rb
app/models/repo.rb
lib/docs_doctor/parsers/ruby/yard.rb
test/fixtures/repos.yml
test/jobs/parse_docs_test.rb
test/test_helper.rb
test/unit/repo_test.rb

Parsing DOCs is extremely expensive on memory and our workers are constantly swapping. The goal is to mitigate this a tad by doing all the known memory intensive work inside of a fork. After we're done the fork goes away and with it, all of it's memory.
If this doesn't help then the next step would be to patch YARD to allow for the ability to incrementally generate docs instead of generating all the docs and loading into memory up front.

Test DOC parsing and move to run in a fork

---

app/jobs/background_inactive_email_job.rb
app/mailers/user_mailer.rb
lib/tasks/schedule.rake
test/functional/user_mailer_test.rb
test/jobs/parse_docs_test.rb
test/test_helper.rb

This SQL query currently accounts for 28% of IO time even though it's only called half as much as the next most frequent query
```
00:19:21.386247 | 28.6%          | 19,761    | 00:00:00.068624 | SELECT  "repos".* FROM "repos" INNER JOIN "repo_subscriptions" ON "repo_subscriptions"."repo_id" = "repos"."id" WHERE (repos.id not in ($2)) GROUP BY repos.id ORDER BY issues_count::float/COUNT(repo_subscriptions.repo_id) DESC LIMIT $1
```
Instead of calling it for every user (since it's the same result set) we can call it once outside of the loop and pass it in.

Move expensive SQL query out of loop

---

app/models/issue_assigner.rb
test/unit/issue_assignment_test.rb

Right now we execute a SQL query for every repo subscribed to multiplied by the number of issues a person wants to receive for that repo.
With this PR we now try to find all of the issues with one query, this reduces the number of queries when sending out issues to the number of repos subscribed to rather than the number of repos subscribed to multiplied by the number of issues.

Fewer SQL queries when assigning issues

---

db/migrate/20191014201819_drop_unused_indexes.rb

```
public.issues            | index_issues_on_number                                         | 198 MB     |           0
public.issue_assignments | index_issue_assignments_on_repo_subscription_id_and_created_at | 370 MB     |           0
public.issues            | index_issues_on_repo_id                                        | 1536 MB    |           0
```

Remove large unused indexes

---

app/jobs/populate_issues_job.rb
app/models/issue.rb
config/initializers/new_framework_defaults.rb
test/unit/issue_test.rb

Getting tons of errors in prod `ActiveRecord::RecordInvalid Validation failed: Repo must exist`
From
```
def self.create_from_github_hash!(issue_hash)
last_touched_at = issue_hash['updated_at'] ? DateTime.parse(issue_hash['updated_at']) : nil
Issue.create!(title: issue_hash['title'], # < =======================
url: issue_hash['url'],
last_touched_at: last_touched_at,
state: issue_hash['state'],
``` 
But my tests pass locally. Lead me to ask this on twitter https://twitter.com/schneems/status/1184291882110726147 and found that the defaults changed and need to be updated in the project 
https://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html

Fix Repo not being created for issues

---

app/jobs/populate_issues_job.rb
app/models/github_fetcher/resource.rb
test/jobs/populate_issues_job_test.rb
test/test_helper.rb
test/unit/github_fetcher/issues_test.rb

This commit gives a Fetcher the ability to pass in an optional retry parameter that will retry a request on failure. This works because random tokens are pulled for each request based off of the git_hub_bub initializer so if one token isn't good, try another for a few times before giving up.

Allow API Fetcher Retry on bad token

---

app/jobs/background_inactive_email_job.rb
app/jobs/populate_docs_job.rb
app/jobs/populate_issues_job.rb
app/jobs/send_daily_triage_email_job.rb
app/models/user.rb
lib/tasks/schedule.rake

- Store the raw ID instead of the global string-thingy in redis
- Only enqueue users that we know have at least have subscriptions. Ideally we would also pre-filter them for ready to receive an email, but we need to refactor some info out of repo_subscriptions so we don't end up with a ton of N+1 queries.
- Only select the info that we need in the queries (i.e. `select(:id)`) for less data transfer from the DB.
- Increase size of batch so that fewer queries need to be run
TODO store `last_sent_at` and `repo_subscriptions_count` metadata to users.

Decrease redis memory needs

---

app/models/github_fetcher/resource.rb
db/migrate/20191017202913_add_removed_from_github_to_repo.rb
db/schema.rb
lib/tasks/schedule.rake

Right now we assume all Repos in Code Triage exist. This task will check each repo to see if it still exists, if not it will mark it for manual review.

Mark Repos removed from GitHub

---

Gemfile.lock
config/initializers/git_hub_bub.rb

Currently EVERY api request to GitHub results in a Query to the database. We can reduce this by a factor of 2000 by storing 2000 tokens in memory and updating them when we run out.
Also rev GitHubBub due to https://github.com/schneems/git_hub_bub/commit/650ec46fe284358e5f83a90a1070b2a9e837201

Reduce DB load on application

---

app/models/repo.rb
test/unit/repo_test.rb

I like the behavior but want to disable to get some metrics so we can fix the underlying memory problem rather than cover it up with a fork.

The `fork` call screws with Scout/Skylight and friends

---

db/migrate/20191025191255_add_updated_at_index_to_issues.rb
db/schema.rb
db/seeds.rb

When pairing for a bit @nateberkopec thought that one of the queries in our `heroku pg:outliers` might not have an index:
```
00:06:22.833704 | 11.1%          | 10        | 00:04:58.761044 | UPDATE "issues" SET "state" = $1 WHERE (state = $2 and updated_at < $3)
```
When we checked, sure enough it didn't have an index on `updated_at`
```
issuetriage::DATABASE=> \d issues
Indexes:
"issues_pkey" PRIMARY KEY, btree (id)
"index_issues_on_repo_id_and_id" btree (repo_id, id) WHERE state::text = 'open'::text
"index_issues_on_repo_id_and_number" btree (repo_id, number)
"index_issues_on_repo_id_and_state" btree (repo_id, state)
```
However when we tried adding one, it didn't actually help. Here's the explain analyze before.
```
issuetriage::DATABASE=> EXPLAIN ANALYZE SELECT count(*) FROM issues …
```

Speed up query by adding index

---

app/jobs/background_inactive_email_job.rb
app/jobs/populate_docs_job.rb
app/jobs/populate_issues_job.rb
app/jobs/repo_based_job.rb
app/jobs/send_daily_triage_email_job.rb
app/jobs/subscribe_user_to_docs.rb
app/jobs/user_based_job.rb
test/jobs/populate_issues_job_test.rb

Scout allows "context" to be added to background jobs https://docs.scoutapm.com/?_ga=2.6482226.1047178103.1572110586-117176759.1572110586#ruby-custom-context
This PR adds two classes, a UserBasedJob and a RepoBasedJob. When you inherit from a UserBasedJob then the user of that the job is processing on is automatically added to the scout context. Same for RepoBasedJob (but with repos instead of users).
I previously added code that allows these jobs to take either an ID or an object. I ported this code to live in the same callback that sets the context for scout.
I was chasing down some Redis memory OOM errors and trying to make smaller jobs. By using an integer instead of an object, we save on the serialization time for generating a globalID object and save for a small amount of space in …

Add context to Scout for background jobs

---

app/jobs/populate_docs_job.rb

When parsing documentation we generate a lot of active record objects:
Most of them are only needed for a split second or two and can then be collected, however due to the QueryCache the objects will live on in memory for the entire duration of the job:
- https://github.com/rails/rails/issues/27002
- https://github.com/rails/rails/issues/28646
This PR disables the Query cache for the populate docs job. 
In the future we need to remove all these N+1 queries from the background doc parse, but for now hopefully this bandaid will at least prevent N+1 objects from being retained in memory for the duration of the job.

Attempt to Reduce memory requirements of Doc Parse

---

.travis.yml
app/jobs/populate_issues_job.rb
db/migrate/20191025030201_add_unique_index_number_repo_id.rb
db/schema.rb
test/fixtures/issues.yml
test/test_helper.rb
test/unit/issue_assignment_test.rb
test/unit/issue_test.rb
test/vcr_cassettes/fetch_issue_comments.yml

Previously we were loading and instantiating issues for every issue pulled from GitHub. With this patch we no longer create issue objects and we've removed the N+1 query for the case where new issues are created.
All updates and creates are now done via `upsert_all`. To accomplish this we need a unique index on [:number, :repo_id] for issues.
cc/ @nateberkopec

Get rid of N+1 queries by using upsert_all

---

Gemfile

From rubocop:
Gemfile:124:1: C: Layout/TrailingBlankLines: 1 trailing blank lines detected.

Fix trailing blank line

---

Gemfile.lock
app/views/pages/_repos_with_pagination.html.slim

By disabling collection caching we can significantly improve the performance of the home page. Performance improvements across 5 different runs range from `1.40x` to `1.58x`. All tests were statistically significant with a confidence interval of 99%. I am extremely confident in these results:
```
$ DERAILED_PATH_TO_LIBRARY=. bundle exec derailed exec perf:library
❤️ ❤️ ❤️  (Statistically Significant) ❤️ ❤️ ❤️
[70736f8] "Disable collection caching" - (4.115744 seconds)
FASTER 🚀🚀🚀 by:
1.5219x [older/newer]
34.2936% [(older - newer) / older * 100]
[ad28f58] "Comment out statsd as well" - (6.2638365 seconds)
Iterations per sample: 200
Samples: 200
Test type: Kolmogorov Smirnov
Confidence level: 99.0 %
Is significant? (max > critical): true
D critical: 0.15174271293851463
D max: 0.83
Output: …
```

Disable collection caching

---

app/controllers/repos_controller.rb
test/integration/adding_repos_test.rb

Allow support for different types of URL including: 
```schneems/wicked
github.com/schneems/wicked
https://github.com/schneems/wicked"
https://github.com/schneems/wicked?files=1" # strip out everything after the ?```

[Close #1145] Updated new repo URL parsing logic 

---

.rubocop.yml
Gemfile.lock

This PR just updates the Rubocop version
#1239

Bump rubocop from 0.76.0 to 0.79.0

---

config/initializers/covid.rb

nextstrain/janus has been deprecated in favor of nextstrain/cli
According to the [README in the nextstrain/janus repo](https://github.com/nextstrain/janus#note-about-deprecation), it has been deprecated and superseded by [nextstrain/cli](https://github.com/nextstrain/cli)
Repo was deprecated, directing people to the current repo

update reference to deprecated codebase in covid.rb

---

app/views/pages/index.html.slim

Simple fix to the homepage language filters that is slightly broken since the introduction of the covid project section.
On the homepage we currently have 2 language filters - one for covid project, other for normal stuff like CodeTriage always had.
Problem is that these 2 filters use slightly different querystring parameters but the view snippet that generates either of them is cached using the same cache key.
This results in both filters working on the same querystring parameter and given the order they exist on the page, right now it is only possible to filter by "language_covid".
By booting the app and clicking around 😭 
I've tried to add a test:
```ruby
test "has filters for both covid and non-covid projects" do
visit "/"
assert page.has_selector?("a[data-query=language_covid]", …
```

Fix filtering by lang with covid and without

---

app/views/pages/index.html.slim
test/integration/filtering_language_test.rb

The number of COVID related projects Is relatively small and I don't think having them here is particularly driving engagement with those projects.
At the same time, I'm seeing that the overall CodeTriage user growth during the pandemic isn't the same as it was before (eyeballing, I could be wrong). 
I'm still open to exposing these repos somehow, but I think people who don't know what CodeTriage is are getting the mistaken impression it's ONLY covid related, which is not the case.
Let's revert back to the old homepage for now

Remove COVID homepage

---

Gemfile
Gemfile.lock

Upgrade Skylight gem to 5.0.0.beta4
https://github.com/codetriage/CodeTriage/issues/1406
With 5.0beta4, we can enable the Skylight for Source Locations feature for your account. This feature will allow your contributors to more easily find out exactly where an expensive operation originated without having to scour your code.
Existing tests pass locally.

Upgrade Skylight gem to 5.0beta4

---

README.md

I fixed a typo in a link in the README where it says "master" when it should say "main."
The README contains an image to a Travis-CI badge:
[![Build Status](https://secure.travis-ci.org/codetriage/codetriage.svg?branch=master)](http://travis-ci.org/codetriage/codetriage)
I changed this link to say "main" instead of "master," since the default branch in this repo is named main:
[![Build Status](https://secure.travis-ci.org/codetriage/codetriage.svg?branch=main)](http://travis-ci.org/codetriage/codetriage)
This fixes the issue of the badge saying "build: error" when it should actually say "build: unknown."
You can see that my changes have fixed the Travis-CI badge by looking at the README in GitHub.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I have read the …

Fixed typo in Travis-CI badge in README

---

Gemfile
Gemfile.lock
app/helpers/repos_helper.rb
app/views/application/_nav.html.slim
app/views/pages/index.html.slim
app/views/pages/what.html.erb
app/views/repos/show.html.slim
app/views/university/example_app.md.erb
app/views/university/rebase.md.erb
app/views/university/reproduction_code.md.erb
app/views/university/squash.md.erb
app/views/users/show.html.slim
test/integration/adding_repos_test.rb
test/test_helper.rb

Email from GitHub
```
[GitHub API] Deprecation notice for authentication via URL query parameters
GitHub
Mar 6, 2021, 4:37 AM (5 days ago)
to Richard
Hi @schneems,
On March 6th, 2021 at 10:37 (UTC) your application (CodeTriage) used an access token (with the User-Agent Faraday v0.17.3) as part of a query parameter to access an endpoint through the GitHub API:
https://api.github.com/user
Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.
Depending on your API usage, we'll be sending you this email reminder on a monthly basis.
Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.
Thanks,
The GitHub Team
```

Update GitHub omniauth

---

app/views/users/token_delete.html.slim

Clarify the point raised in https://github.com/codetriage/CodeTriage/issues/1246
Just changed text on account deletion page.
- https://github.com/codetriage/CodeTriage/issues/883
- https://github.com/codetriage/CodeTriage/issues/710
- https://github.com/codetriage/CodeTriage/issues/409
- https://github.com/codetriage/CodeTriage/issues/144
- https://github.com/codetriage/CodeTriage/issues/135

The only way to unsubscribe is account deletion

---

app/views/repos/show.html.slim

This moves the "Stop Triaging" button above the subscribers list and beneath the "Triage Docs!" section.
https://github.com/codetriage/CodeTriage/issues/1573
I agree with the person who opened the issue.  When I've wanted this function, I don't think to scroll all the way down at first and wished it was easier to access.
I started the app and went to a repo's show page.

Moves the "Stop Triaging" button farther up on the page

---

app/controllers/repos_controller.rb
app/views/repos/new.html.slim
test/integration/adding_repos_test.rb

In order to prevent the situation described in issue #1499, I changed repo controller to not require the user to be logged in to see the new repo view, and I added conditional rendering in the new repo view to show a message that the user needed to be logged in to add the repo to CodeTriage, and provided a CTA button that begins the Github login flow.
#1499 
This change is meant to avoid the abrupt authentication error that occurs when an unauthenticated user visits the new repo view.
I tested this locally in a docker container, and ensured that the added test passed.
Unauthorized Users:
After logging in using new button:
cc @bdougie @filiptronicek @0-vortex

new repo view for unauthed user

---

CONTRIBUTING.md
app/controllers/users_controller.rb
app/mailers/user_mailer.rb
app/views/layouts/mail_layout.html.erb
app/views/layouts/mail_layout.text.erb
app/views/user_mailer/daily_docs.md.erb
app/views/user_mailer/invalid_token.md.erb
app/views/user_mailer/poke_inactive.html.erb
app/views/user_mailer/poke_inactive.text.erb
app/views/user_mailer/send_daily_triage.md.erb
app/views/user_mailer/send_triage.md.erb
app/views/user_mailer/spam.md.erb
app/views/users/_form.html.slim
db/migrate/20220908011235_add_htos_promo_to_user.rb
db/schema.rb
test/mailers/previews/user_preview.rb

Allows users to mute book promo emails. Also switch email signature to a Twitter account. Having the emails come "from me" isn't really accurate and linking them to my blog isn't terribly useful as I write a bunch about Ruby and non-open source things. I'm instead directing to a dedicated open source Twitter account that can be more focused on open source content.

HTOS muting & switch email signature to a twitter account

---

app/controllers/users_controller.rb
app/views/users/show.html.slim

Previously any request to `/users/<id>` would trigger a log in flow if you're not logged in. In https://github.com/omniauth/omniauth/pull/1010 (or somewhere around there) omniauth removed the ability to use a GET request to log in at all. Now all login requests must be done via GET. 
This means you cannot redirect to a login endpoint, you must drop the user off somewhere there is a form and they must manually click it to trigger a POST. 
That's what this PR does. If you try to edit or view your user account without being logged in today: it will give you a 404 error page with a cryptic error message.
```
Not found. Authentication passthru.
```
(Which I think omniauth could improve A LOT, FWIW). 
Anywhoo, to move forward I'm replacing the prior `authenticate_user!` before filter with one …

Soft landing for non-post omniauth requests

---

app/mailers/user_mailer.rb

From is already specified as a default. We don't need to specify it again.

Use default from

---

app/mailers/user_mailer.rb

Spam assassin doesn't like when reply-to is from from a freemail provider and doesn't match the `from`. It's hurting deliverability.
People can still get in contact via twitter and other venues.
I'm not sure where the "LONG_HEX_URI" is coming from though.
```
Content analysis details:   (6.9 points, 5.0 required)
pts rule name              description
---- ---------------------- --------------------------------------------------
1.1 URIBL_GREY             Contains an URL listed in the URIBL greylist
[URIs: sendgrid.me]
-0.0 RCVD_IN_MSPIKE_H2      RBL: Average reputation (+2)
[167.89.26.35 listed in wl.mailspike.net]
0.2 HEADER_FROM_DIFFERENT_DOMAINS From and EnvelopeFrom 2nd level
mail domains are different
-0.0 SPF_PASS               SPF: sender matches SPF record
0.0 SPF_HELO_NONE …
```

Remove reply-to feature

---

app/models/label.rb
app/models/repo.rb
app/models/repo_label.rb
app/services/repo_label_assigner.rb
db/migrate/20221004010742_create_labels_table.rb
db/migrate/20221004010749_create_repo_labels_table.rb
db/schema.rb
lib/tasks/schedule.rake
test/unit/repo_labels_assigner_test.rb
test/vcr_cassettes/fetch_labels_for_repo.yml

@schneems thanks for the opportunity to contribute! 
Adds two new tables: `repo_labels` and `labels` to store label data
Created a new service class to store and associate labels for repos
if the same `label` exists on multiple `repos`, it does not make
duplicate `label` records.
Add simple rake task to iterate through all `repos` `in_batches` and fetch one by one
Partially resolved #1680 
People should be able to target Hacktoberfest 
Some simple integration testing of the newly created PORO

Add Support for Storing Repo Labels

---

app/mailers/user_mailer.rb

Prevent emails from being sent with the wrong argument by requiring kwarg presence.

Remove default argument

---

.rubocop.yml
Gemfile.lock

Previously we were getting this warning/error:
```
$ be rake test
[Scout] [10/08/22 19:32:44 -0500 rschnee-ltm4wff.internal.salesforce.com (18670)] INFO : Failed loading configuration file (/Users/rschneeman/Documents/projects/codetriage/config/scout_apm.yml): Unknown alias: defaults. ScoutAPM will continue starting with configuration from ENV and defaults
Run options: --seed 11077
................................................................................................................................................................................
Finished in 9.171450s, 20.4984 runs/s, 38.9251 assertions/s.
188 runs, 357 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Minitest to /Users/rschneeman/Documents/projects/codetriage/coverage. 1066 / 1515 LOC …
```

Upgrade VCR

---

test/test_helper.rb

Tests were failing due to missing VCR stub. This fixes by providing information so we don't try to hit GitHub's API.

Fix tests broken by prior commit

---

app/controllers/doc_methods_controller.rb

While making tests for the class (#943), I've noticed that this method wasn't working properly because of two errors:
- on line 36 the search for a `RepoSubscription` was not being made correctly, which would consequently lead to the `sub` variable being nil.
- on line 39 the `if` conditional was raising an error in case the condition wasn't met instead of just executing the `else` instruction. To fix it I've prevented the condition of raising an error.

fix click_source_redirect method on doc_methods_controller

---

CONTRIBUTING.md

I guess default branch has been changed from `master` to `main`, right? 
Currently, default is `main` and target branch of each PR is also `main`.
So I updated the document.
no issue, is it right?
`master` branch has not deleted today. (BTW, It sounds good to delete master branch if maintainer is OK)
If newbie or creator or who follow the CONTRIBUTING.md faithfully might make a PR to master branch.
I can prevent it by updating document.

Update default branch name from `master` to `main` in CONTRIBUTING.md

---

lib/dependency_parser/ruby/parse.rb
test/dependency_parsers/ruby_parser_test.rb
test/vcr_cassettes/dependency_parser/rubygems.yml

Dependency parsing for #1686
Uses Bundler gem for parsing, parses only name for now, we should probably extract URL for repos.
- #1686 Gemfile.lock, more languages to come, stay tuned ;) 
An initial stub to get the dependency parsing running
- invalid file + a tiny Gemfile.lock, might need more testing

Add Gemfile.lock parsing for dependency parser

---

config/initializers/inflections.rb
lib/dependency_parser/php/parse.rb
test/dependency_parsers/php_parser_test.rb
test/fixtures/files/composer.lock

Add PHP dependency parsing from `composer.lock` files.
This extracts dependencies from `composer.lock` (including dev dependencies from `packages-dev`) and provides names, github urls and descriptions.
We want to have a list of suggested repositories to contribute to for Code Triage users.
Just a small `composer.lock` file generated by creating a new Symfony project then removing 90%+ dependencies. Probably needs more testing in real life.

Add PHP dependency parsing

---

app/models/random/cached_id_query.rb
config/initializers/sidekiq.rb

Heroku upgraded Redis instances to Redis 7. Premium redis instances now enforce TLS (SSL), which is a good thing, however the certs are self-signed which causes a validation error.
The documented fix is to disable the validation. https://devcenter.heroku.com/articles/connecting-heroku-redis#connecting-from-sidekiq
Close #1787

Ignore self signed Redis certs

---

config/initializers/sidekiq.rb

The prior commit only applied SSL verification logic to all environments except production. This fix applies to production.
Close #1787

Ignore self signed Redis certs in prod

---

app/controllers/pages_controller.rb
app/views/application/_nav.html.slim
app/views/pages/topic.html.slim
config/routes.rb
test/functional/pages_controller_test.rb

Added view for repos labeled Hacktoberfest. View is accessible from a dropdown in the navbar
https://github.com/codetriage/CodeTriage/issues/1680
Trying to tackle the linked issue (creating view for repos with some specific label). Proposing to manually maintain list of eligible labels (in this case `hacktoberfest`) because showing all available labels & use it similarly like language filter might make it look very crowded IMO
Sampled labels from some repos linked below
Added unit tests for invalid topics usage in route
navbar view
signed in user
unsigned in user
Sampled labels from some repos
- [ x] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.

View For hacktoberfest labeled repo

---

Gemfile
Gemfile.lock

This pull request addresses issue https://github.com/codetriage/CodeTriage/issues/1782 by reorganizing and categorizing the gems in the Gemfile to improve understanding and maintainability. The changes ensure that related gems are grouped together, making it easier to identify their purpose and the application components they relate to. I have also moved certain gems, such as minitest and yard, to more specific environment groups for better dependency management.
Please review the changes and let me know if any adjustments are needed. Thank you for considering my contribution.

Reorganize gemfile
